---
name: Pull request and push coverage reports

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to commit the changes

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # TODO: to do this we need to have access to a running copy of hydrus...
      # - name: Install dependencies
      #   run: npm install vitest @vitest/coverage-v8 fs-jetpack

      # - name: Run Unit Tests
      #   run: npx vitest --coverage

      - name: Publish Statements Badge
        uses: wjervis7/vitest-badge-action@v1.0.0
        if: success() || failure() # run whether steps succeed or not
        with:
          result-type: statements
          badge-text: 'Coverage (Statements)'
          upload-badge: false
          vitest-config-path: 'vite.config.mjs'
          summary-path: 'docs/coverage/coverage-summary.json'
          badge-path: 'badges/statements.svg'

      - name: Publish Lines Badge
        uses: wjervis7/vitest-badge-action@v1.0.0
        if: success() || failure() # run whether steps succeed or not
        with:
          result-type: lines
          badge-text: 'Coverage (Lines)'
          upload-badge: false
          vitest-config-path: 'vite.config.mjs'
          summary-path: 'docs/coverage/coverage-summary.json'
          badge-path: 'badges/lines.svg'

      - name: Publish Functions Badge
        uses: wjervis7/vitest-badge-action@v1.0.0
        if: success() || failure() # run whether steps succeed or not
        with:
          result-type: functions
          badge-text: 'Coverage (Functions)'
          upload-badge: false
          vitest-config-path: 'vite.config.mjs'
          summary-path: 'docs/coverage/coverage-summary.json'
          badge-path: 'badges/functions.svg'

      - name: Publish Branches Badge
        uses: wjervis7/vitest-badge-action@v1.0.0
        if: success() || failure() # run whether steps succeed or not
        with:
          result-type: branches
          badge-text: 'Coverage (Branches)'
          upload-badge: false
          vitest-config-path: 'vite.config.mjs'
          summary-path: 'docs/coverage/coverage-summary.json'
          badge-path: 'badges/branches.svg'

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated coverage badges
          file_pattern: 'badges/*'